apiVersion: v1
kind: Pod
metadata:
  name: postgres-pod
  labels:
     name: postgres-pod
     app: voting-app
    
spec:
  containers:
  - name: postgres
    image: postgres:9.4
    volumeMounts:
    - mountPath: /var/lib/postgresql/data
      name: db-data
    ports:
    - containerPort: 5432   

    



    
       


