apiVersion: v1
kind: Pod
metadata:
  name: redis-pod
  labels:
     name: redis-pod
     app: voting-app
    
spec:
  containers:
  - name: redis
    image: redis
    volumeMounts:
    - mountPath: /data
      name: redis-data
    ports:
    - containerPort: 6379

    volumes:
    - name: redis-data



    
       

























apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: redis
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
      - image: redis:alpine
        name: redis
        volumeMounts:
        - mountPath: /data
          name: redis-data
      volumes:
      - name: redis-data
        emptyDir: {} 
