apiVersion: v1
kind: Pod
metadata:
  name: worker-app-pod
  lebels:
    name: worker-app-pod
    app: voting-app

spec:
  containers:
  - name: worker
    image: dockersamples/examplevotingapp_worker
   
